<?
use Icinga\Module\Monitoring\Object\Service;
use Icinga\Module\Monitoring\Object\Host;


?>
<div class="controls">
  <?php if (! $this->compact): ?>
    <?= $tabs; ?>
  <?php endif ?>
</div>


<div class="content">


    <h1>SLA Reports</h1>
    <div style="float:right">
        <div class="legend unknown-ack" >unknown</div>
        <div class="legend critical-ack" >critical</div>
        <div class="legend warning-ack" >warning</div>
        <div class="legendtext" >Acknowledged:</div>

        <div class="legend unknown" >unknown</div>
        <div class="legend critical" >critical</div>
        <div class="legend warning" >warning</div>
        <div class="legend ok" >ok</div>
        <div class="legendtext">Legend:</div>

        <div class="legendtext">&#8632; = Host Down and Acknowledged</div>    
        <div class="legendtext">&#10004; = Acknowledged</div>
        <div class="legendtext">&#8986; = In Downtime</div>
    </div>

<h2>SLA Report</h2>
     <div>

<?php

function prettyPrint ($arr) {
  echo '<pre><code>';
  print_r($arr);
  echo '</code></pre>';
}
 
  foreach ($this->recentAlerts as $alert) {
      ?>
    <li><?php prettyPrint($alert); ?></li>
<?php } ?>
      </div>
<br clear="all"/>
